### ISSUE TITLE
Add new tab bug

### ISSUE THREAD

**Issue by zfedoran** [MauriceConrad/Photon#1]
Awesome library!

I did find a small issue though, I'd like to be able to put the `+` button for new tab items on the left rather than the right, doing so causes a number of issues if you click the `X` button on an active tab item.

https://jsfiddle.net/arxqm737/1/

**Comment by zfedoran** [comment]
https://github.com/zfedoran/PhotonKit-Components/commit/39fb29ce26e12953a25663a7a27ca0d4e4d80200

**Comment by ElyaConrad** [comment]
Also fixed in the new version of tab group. https://jsfiddle.net/Loo3pyuo/
