### ISSUE TITLE
NEW RELEASE 1.0

### ISSUE THREAD

**Issue by ElyaConrad** [MauriceConrad/Photon#15]
# Photon 1.0 RELEASE

## Dear Photon User!

I am very proud to announce the release of Photon version 1.0! You are a follower of Photon and maybe you already know my extension framework „PhotonKit Components“ that extends the original Photon project on a high level. Sadly the original developer @connors was not abled to accept my contributions or answer me at least one time because he seems to be inactive since more than 2 years. This is very sad because Photon is a great tool to design native looking UI’s and there was a lot to do.
I was the only active developer who still keeps the project up to date.

![ShowReel](https://dev.maurice-conrad.eu/img/photon/demo.png)

Somedays I thought about the future of the project and the last commitment of @connors was 2 years ago. I realised that the only solution for the future of the project would be a complete new version 1.0

This release is a hard fork of the original project that redefines everything hardly and replaces the PhotonKitComponents project I made.

## Getting Started

```bash
npm install electron-photon
```

Just have a look at the „ShowReel“ application or ask me for questions ;-)

[GitHub](https://github.com/MauriceConrad/Photon)

[NPM](https://www.npmjs.com/package/electron-photon)

### Questions? Ideas?

[conr.maur@googlemail.com](mailto:conr.maur@googlemail.com)

**Kind regards,**
<br>**Maurice Conrad**

**Comment by lukesUbuntu** [comment]
Thank you!

**Comment by parro-it** [comment]
Thank you, this are great news!

**Comment by jonaaix** [comment]
Nice work man!

**Comment by burakcan** [comment]
Thank you for your efforts but why did you gather our emails and spam?

**Comment by ElyaConrad** [comment]
@burakcan Sorry, I sent the stargazers of the original repo an email, of course you are a part of them. This is not totally great for the people who already read this post, I know... But I cannot exclude several mail addresses from a  list of 3385 addresses.

**Comment by burakcan** [comment]
I don't believe those stargazers gave you permission to spam them? Starring a repo doesn't mean "I agree to be spammed about this repo or forks of this repo"
