### ISSUE TITLE
Warning: Unknown props `keyFromValue`, `fillDefaults` on <div> tag.

### ISSUE THREAD

**Issue by uvlek** [MauriceConrad/Photon#16]
I am using your package and have error here:
Warning: Unknown props `keyFromValue`, `fillDefaults` on <div> tag.
/home/ago/fetchit/Need4Store/node_modules/electron-photon/helper.js:86

Can you help me how fix it?

**Comment by ElyaConrad** [comment]
Hey @uvlek I cannot reproduce your error? When does it happen? Does everything work as expected?
The methods `fillDefaults` or `keyFromValue` are both prototype extensions for the `Object` class. `fillDefaults` fills up an object with default properties deeply. `keyFromValue` get's the first key whose property has the given value. I do not get any error.

**Comment by uvlek** [comment]
This happens when Array.prototype , i am using webpack maybe it broke
somehow. Also i have a problem with custom elements used in jsx react,
maybe you know how avoid error?

1 мар. 2018 г. 13:54 пользователь "Maurice Conrad" <notifications@github.com>
написал:

**Comment by ElyaConrad** [comment]
I am not sure but it seems to be problem with JSX: if you try out the "ShowReel" app included in my repo or just write a plain app you will see that there is no error. I will try out Photon on JSX and check wether I get any kind of error and if I will do my best to fix.

I do not know what exactly is meant by "Also i have a problem with custom elements used in jsx react". Do you have problems with the elements that re based on JSX or problems with my custom elements? This seems to be not a problem with Photon but with JSX..? I will try it out and do my best :)

**Comment by tadeubdev** [comment]
I have the same problem! And that issue is the unique that I has found.
