### ISSUE TITLE
Need more icons

### ISSUE THREAD

**Issue by pvitaliy84** [MauriceConrad/Photon#17]
Hello. At first, thanks for your work.
On "https://github.com/MauriceConrad/Photon/tree/master/dist/PhotonNavigation" I see only 6 icons. Where I can get the other 200 icons?

![icons](https://user-images.githubusercontent.com/29367252/36608647-9f0499da-18f4-11e8-9dc0-1177f073f92c.jpg)
Thanks yet, you are cool!

**Comment by ElyaConrad** [comment]
The icons Connor used are bundled within font files.
You could use them from the original repo at https://github.com/connors/photon/tree/master/dist/fonts

The reason why I did not included them is, that I the solution using fonts for icons is not a modern one and I would prefer embedding icons using inline svg. To get SVG icons you could use sites like https://www.flaticon.com/ (Free) or https://icons8.com (paywall)

This is recommended but my photon-original.css file includes the original icon classes. Just the font is not included in repo. Therefore you could use the original font files from connors instead :)
