### ISSUE TITLE
dropdown.css missing

### ISSUE THREAD

**Issue by ekelundcc** [MauriceConrad/Photon#18]
Hi!

Thanks for your good work!

dropdown.css seems to be missing in ./node_modules/electron-photon/dist/PhotonMenu/

BR / Fredrik

**Comment by ElyaConrad** [comment]
I fixed it. There is no need for a single line CSS for the drop down menu, therefore I removed the dependency.

**Comment by ekelundcc** [comment]
:) Thanks!
