### ISSUE TITLE
Pane CSS has "padding" due to overflow: scroll

### ISSUE THREAD

**Issue by mikerogne** [MauriceConrad/Photon#32]
Put together a demo video: https://d.pr/v/ZJ3o5j

Is nobody else experiencing this?

**Comment by jonaaix** [comment]
This is the normal behaviour if you set `overflow: scroll`. 
If you want to make it scrollable just in case there is something to scroll, just set `overflow: auto;`

**Comment by mikerogne** [comment]
> This is the normal behaviour if you set `overflow: scroll`.
> If you want to make it scrollable just in case there is something to scroll, just set `overflow: auto;`

Yeah, I just realized that this is actually the default behavior and matches the screenshots on the main page as well (https://mauriceconrad.github.io/Photon/). Definitely not what I want. I fixed it in the CSS, but I ended up just switching back to the original http://photonkit.com/ package despite the fact it is basically unmaintained.
