### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by MogliDerZauberKoenig** [MauriceConrad/Photon#35]
Hi,

iam trying to use Photon, but after I wrote this line(const Photon = require("electron-photon");) in my script I get this error.

<img width="519" alt="bildschirmfoto 2018-12-22 um 01 35 32" src="https://user-images.githubusercontent.com/17054132/50368555-5323ed80-058a-11e9-92a2-9416b5f551dd.png">

i also installed the package via npm

**Comment by MogliDerZauberKoenig** [comment]
Oh man I found the issue... you can close this

**Comment by juvivas** [comment]
Hi, i have the same problem. how could you solve it?

**Comment by guilherme-gm** [comment]
@juvivas I ran into the same problem, looks like you shouldn't put the require line in your main.js but in an extra js that is loaded by your html file.

Something like this:
index.html:
```
<script src="ui.js"></script>

<ph-window>
    <!--Top header bar here-->
    <tool-bar type="header">
        Toolbar Header
    </tool-bar>
    <!--Window content here-->
    <window-content>
        Window Content
    </window-content>
    <!--Bottom footer bar here-->
    <tool-bar type="footer">
        Footer Header
    </tool-bar>
</ph-window>
``` 

ui.js:
```
const Photon = require("electron-photon");
```

**Comment by ElyaConrad** [comment]
That is true. Because the Node-Module works with your document object model, it can not be required in a scope without a DOM.
