### ISSUE TITLE
No inner border shown for active buttons if there are 2 elements only

### ISSUE THREAD

**Issue by vasyl-shumskyi** [MauriceConrad/Photon#5]
Looks like inner-border is missing for 2 stacked active buttons. Meanwhile, border showing nicely for 3+ stacked active buttons:

<img width="822" alt="screen shot 2017-05-23 at 21 41 26" src="https://cloud.githubusercontent.com/assets/2331802/26370596/fe6517e2-4000-11e7-89a2-b91927dc4ab9.png">

https://jsfiddle.net/hxpkrxd7/

**Comment by ElyaConrad** [comment]
I will do my best to fix ist soon as possible! Please keep in mind that it's always not easy to implement "workarounds" for borders on retina displays. And this problem only exists on retina displays.

But if you take a look at native macOS applications, segmented controls that are activated more than once doesn't show borders between the activated segmented buttons.

<img width="260" alt="bildschirmfoto 2017-05-24 um 23 16 43" src="https://cloud.githubusercontent.com/assets/12884009/26425978/12026a9e-40d7-11e7-9d8b-00df9bbc7abd.png">

The problems is that I use 'box-shadow' to create "hairline borders" for retina displays(Chromium doesn't supports 0.5px border). And at the moment I can't regulate the scaling factor on x or y axis of a box shadow. Therefore it's not possible to fix it at the moment without changing the workaround.

**Comment by vasyl-shumskyi** [comment]
Thanks for your reply! 

I really need to fix this somehow and will be fine even with hardcoding, if you show me what needs to be changed

Because it just looks now like one wide button...

<img width="328" alt="screen shot 2017-05-25 at 11 01 15" src="https://cloud.githubusercontent.com/assets/2331802/26441625/f8f4070c-4139-11e7-9277-456a42336c8e.png">

Thanks again!

**Comment by ElyaConrad** [comment]
Okay, but what exactly do you need?
Do you want the borders even when cocoa doesn't looks so? Okay, I totally understand. To implement something like this, I have to rethink the whole workaround.

But I will do my best to implement it :)

**Comment by ElyaConrad** [comment]
Okay, there is a solution now.
I use background-image with SVG to set the new hairline borders.
Now, you have the possibility to choose if you want the borders or not. Just add the class "separated" to the btn-group parent element.

Look at: https://jsfiddle.net/rbg0q4b1/

(Please use Electron or Chrome) The new code is published ;-) https://github.com/MauriceConrad/PhotonKit-Components/tree/master/Photon-Components/segment

**Comment by vasyl-shumskyi** [comment]
That's wonderful! Just tested new code and it looks amazing! Thanks for the blazingly quick workaround
