### ISSUE TITLE
Passive unclickable button

### ISSUE THREAD

**Issue by vasyl-shumskyi** [MauriceConrad/Photon#6]
I am trying to figure out what is the best way to implement nicely looking inactive unclickable buttons in buttons segment... Can you assist? 

Below `Back` and `Continue` regular buttons are innactive: 

![image](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/osx-elcapitan-security-privacy-filevault-recovery-key-sheet.png)

Thanks as always!

**Comment by ElyaConrad** [comment]
Thank you for your improvement! 

This was very easy to implement. Now, you can use the HTML5 "disabled" attribute for any button-sytem ;-) 

Look at this example: https://jsfiddle.net/sm9qpna8/

**Comment by vasyl-shumskyi** [comment]
Heh :) Cool!

**Comment by ElyaConrad** [comment]
Okay, there was still a new bug that an "btn-active" doesn't show any effect if you press the mouse (:active pseudo class). Also now there is now no effect at a disabled button for :active (Some browsers doesn't prevents this by default)

**Comment by vasyl-shumskyi** [comment]
Wonderfully simple solution for btn-system... 
Works partially for buttons segment - the text wasn't grayed out, when `disabled` used
https://jsfiddle.net/2ej7d99h/

**Comment by ElyaConrad** [comment]
Nope, my solution doesn't works in any way for segmented controls ;-) It's just fact that Chromium generally prevents any mouse click events on a `disabled` element and therefore there is no possibility  to become the pseudo class `:active` for such an element. That is a nice feature but not **my** solution 😜. As you said correctly, the font color doesn't becomes grey. But also the border and the backkround-color are different in `disabled` state if you take a look at native macOS Cocoa.

But the idea to support segmented controls with `disabled` is not bad. Thank you! I will do it soon ans possible! :)

**Comment by vasyl-shumskyi** [comment]
Cool! Thanks :+)

**Comment by vasyl-shumskyi** [comment]
Quick and dirty solution for now is style overriding.
Its not affecting button background color, just text: 

<img width="250" alt="screen shot 2017-05-30 at 19 12 10" src="https://cloud.githubusercontent.com/assets/2331802/26593233/0a96926e-456c-11e7-8735-0809d0435462.png">

```
<button class="btn btn-segment" style="color:gray" disabled>Btn C</button>
```
https://jsfiddle.net/n2t0schd/

**Comment by ElyaConrad** [comment]
@vasyl-shumskyi Hey, sorry for waiting so long but I was very busy.

Look at the new code, or just at this fiddle: https://jsfiddle.net/95hj625x/

Hope, you enjoy! Have a nice day :)
