### ISSUE TITLE
input type number

### ISSUE THREAD

**Issue by sandor** [MauriceConrad/Photon#9]
Would be great to have a suffix/prefix option for the input type – something like this:

```
<input type="number" suffix=" px" prefix="10x " ng-value="canvas.getWidth()" ng-model="width">
<div class="stepper">
              <button></button>
              <button></button>
</div>
```

Also it would be awesome if we could simply combine the stepper with the input – something that the xel-toolkit is doing with tehyr x-numerinput (https://xel-toolkit.org/elements/x-numberinput):

```
<x-numberinput value="100" suffix=" px">
  <x-stepper></x-stepper>
</x-numberinput>
```

How would you connect the stepper buttons to the input right now btw.?

**Comment by ElyaConrad** [comment]
If we have a look at my code example in 'Photon-Components/input", we'll see that you can select the input within in the 'stepper' div's "data-input" attribute. Just use a querySelector there :)

Please remember that every folder of "PhotonKit-Photons" is a valid Electron app that displays detailed information and documentation about the component.
But as I remember, Theresia also a README.md containing this kind of Information. If you're missing some documentation please tell me ! ;)

**Comment by ElyaConrad** [comment]
And something like suffixes and prefixes wouldn't be a good idea because it doesn't fits into the idea of HTML. The stepper 'div' is related to an input element using the "data-input".
Because of that it's not a problem to put some 'span' elements between the input and its related stepper 'div'.

To fix your problem in this way would be much cleaner und nicer.

And referring to your attributes: I don't know what "ng-value" means and all of your attributes are invalid HTML5. I would never define a new attribute without the required "data-" prefix. Please read W3's official documentation about this: https://www.w3schools.com/tags/att_global_data.asp

**Comment by sandor** [comment]
Thanks Maurice, will have a deeper look at the examples etc. – sorry for my ignorance.

Regarding suffixes: we are building here an electron app, so something that would mimic the macos UI UX. Suffixes are very common at least in the context of graphics related apps. Just as an example a screenshot from apples Keynote inputs... My2c!

The attributes you are mentioning (starting with ng-xxxxx) are defined and used by AngularJS. We are using Angular to build the single page app for electron and these are some of the data attributes that makes life a bit easier :-) The "suffox" "prefix" attributes are defined by the xel-framework – so nothing I could change...

Thanks again!
![apple](https://user-images.githubusercontent.com/476224/28205460-6e7061be-6882-11e7-930d-443808d88133.jpg)

**Comment by ElyaConrad** [comment]
Oh sorry but now I understand your problem! Sorry I thought you mean just st something like a span.

This is an interesting point and I will do it when I'm back at home. 

Absolutely sorry That I misunderstood you :)

**Comment by ElyaConrad** [comment]
Hey :) Let#s have a look at the new update.

Or just open https://jsfiddle.net/dujw6gyL/

As you can see a suffix feature is implemented and works still out of the box.

Questions? Ask me :)

**Comment by sandor** [comment]
Very cool Mate! Your fiddle is not working in Safari (whyever) but is working nicely in Chrome. Good job :-)

**Comment by ElyaConrad** [comment]
For me it works in Safari but maybe you're not using ECMAScript > 6 (Belongs to an old version of safari).
This matters because I use [Getter]'s and [Setter]'s and they're a Part of ECMAScript 6 :)

**Comment by sandor** [comment]
OK Safari 10.1.2 did it... THANKS!
